language: node_js
node_js:
- node
before_script:
- npm install -g npm
- npm ci
script:
- npm run build-lib
before_deploy:
- cd dist/firebaseui-angular-library
deploy:
  provider: npm
  skip_cleanup: true
  email: info@rjenni.ch
  api_key:
    secure: GNWI7rGIzWSPxrQac41/KP0m1q8AGzSuahMWF6b6ShEu31qB5RmMJMrw2xx8iRX6dSg9pzbuoeLnk7wPHajbVVldrdVtOIzlEgO0LyK3M36i62rJJGTAHAZvVJV6cAKKidPZvzAB6xf6KrGESBhblGtmdLG5G+X0OdtiL4zyuCqwKg8J+GRsWqpzFpVgSBVKNOcEIqwZ6z+L5vGoDwHYTxncKRGupwKzK5kcfPjSkoToeNAl1NWuvKYIty4i7UhbfN40jetxT395u9xFugCNa6eoN4uJyIqBIm563JZxAggFSeNxznONkn3aEr7FzkEGM17zChRacyN8a3grhhQpNfXnFGX5xARGA7w6piFiFCVzKKi61bz55kZDrxK1apOxmEY7IzfRO7FRaxqyahirPiY9bIA52yWp2fN8leaG1m59ZdeSKUowHntFh9fgZuzYVYsmkfq5fnAPm4Cq4rGpweR3JhqAdOiRxPMcQQC9+hv1cu+5SWpo5ITNVYYgHDUUrfWuQJO6TFJxSp61pdfj3Iv62YLiT+S8PjGEH5NAtsJCu0Lvnv89Ow7z4DlzyMbFs2rsSEPK+8kfEfe0TmxGrEAerkM9HfLZOepfvu0+y3a3TSJtqrhz+YGHDXxVW0R1ZpSnPvQq2HsVdr9RsKwJUEMkyflkdd6kBU9a5KYVYa0=
  on:
    branch: master
    tags: true
notifications:
  email:
    recipients:
    - "$EMAIL"
    on_failure: always
    on_success: always
