language: node_js
node_js:
- node
before_script:
- npm install -g npm
- npm ci
script:
- npm run build-lib
before_deploy:
- cd dist/firebaseui-angular-library
deploy:
  provider: npm
  skip_cleanup: true
  email: info@rjenni.ch
  api_key:
    secure: PXSuzM0qgZlM0K80UYebUk0PMaAB53aaM4MVHf2wU5VtKtxuZOzuwMx3Gby5ea64nmdx23FbfCPP5bzRZGN1RKS/lF7Q61uxfbbv4jypObGt/hUyc2gDRYxfORwaTu9HfwhtWQTiXKksgtPTdTapN6/fbzshvgDfkd3NGPn/fE/mSZ9hRum/fvghL8bWTsMqb0QQioqaGajBthSd6agtUlm7NXvROtik8fQ8ukwCJvFXzrVmW/hT9i0HSuRbhTnx3IhiT296F9V0YgsWUVxH+Z7IgpTJhBQJofiv2jfMORT0Lwt4UrrnicZNYxpcxyNu1zrt7rtqzC9r6Kp2ZBib4CTEEU7TqrmriCWAdIk2vHrtXckN0M2nbxAO4tQ5GuepFPdVy2gMbMhYWJgrT2Ip7dxDQ7Pq4TjsqHAmQDcympSayeQTi7/AzyzJXgh+PEyrihEFY7YCnSLkjCzKvpZfDxVLhfpoyyhn0B+tUrl5hnGo7uyVFK8ZuARX8VY5BbOevskbiGiN3/qJNf6mhnDY8wdg9I4VQ34wDy7Z314XWMQT+YykKlmn4nG8eogkeyfLT4ScTwJ3Z/YN7OavhRaTALOSJPjHYBaIdoT8ot3dOUgFqTJ7p+KBinAmbAWZYMJdUTqlM3N0Qt5Ln1XKuLLWcmNtKkwB0EckQgWZ1uVwgJs=
  on:
    branch: master
    tags: true
    repo: RaphaelJenni/FirebaseUI-Angular
notifications:
  email:
    recipients:
    - "$EMAIL"
    on_failure: always
    on_success: always
